FROM python:3.10-slim

# Define o diretório de trabalho
WORKDIR /app

# Atualiza os pacotes e instala dependências necessárias para psycopg2
RUN apt-get update && apt-get install -y \
    libpq-dev gcc build-essential --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copia os arquivos do projeto
COPY . /app

# Atualiza o pip para a última versão
RUN pip install --upgrade pip

# Instala as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Expõe a porta 8050 (padrão do Dash)
EXPOSE 8050

# Comando padrão para iniciar a aplicação
CMD ["python", "app.py"]

